name: my workflow
on: push
jobs:  
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
    - name: Test
      run: echo $GITHUB_SHA_SHORT
    - name: Env-test-file
      run: |
        echo "test main go file 0 12" > file
        cat file
        TEST=$(cat file) 
        echo "my env file inside $TEST"
        
        
        
