name: my workflow
on: push
jobs:
  run-file:
    runs-on: ubuntu-latest
    steps:
    - name: create file
      run: echo "mylast try 33" > file3
    - name: Test
      run: |
        export TEST=$(cat file3)
        echo $TEST
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
    - name: Test
      run: echo $GITHUB_SHA_SHORT
    - name: Env-test-file
      run: |
        echo "test main go file 0 12" > file
        cat file
        TEST1=$(cat file) 
        echo "my env file inside $TEST1"
    - name: test curl command 
      run: |
        #TEST=$(cat file3)
        echo $TEST
        curl -d '{"job":"'"$TEST"'"}' -H "Content-Type: application/json" -X POST https://reqres.in/api/users | python3 -m json.tool

        
        
        
        
        
